services:

    app.block.random:
        class: AppBundle\Block\RandomBlock
        arguments:
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.search'
        tags:
            - { name: landing_page_field_type.block_type, alias: random }
